apiVersion: v1
kind: Namespace
metadata:
  name: demo
---

apiVersion: v1
kind: Secret
metadata:
  name: postgre-secret
  namespace: demo
type: Opaque
stringData:
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: supersecret
  POSTGRES_DB: appdb
---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: demo
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: demo
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgre-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgre-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgre-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: demo
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 64Mi
              cpu: 50m
          readinessProbe:
            httpGet:
              path: /get
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status/200
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: demo
data:
  index.html: |
    <!doctype html>
    <html>
    <head>
      <meta charset="utf-8" />
      <title>K8s Demo Frontend</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 2rem; }
        code { background: #f4f4f4; padding: 4px 8px; border-radius: 4px; }
        .ok { color: #2f855a; }
        .err { color: #c53030; }
      </style>
    </head>
    <body>
      <h1>Frontend ✓</h1>
      <p>This static page is served by NGINX in Kubernetes.</p>
      <p>Click to call <code>/api/get?demo=true</code> (routed by Ingress to the backend service).</p>
      <button id="btn">Call API</button>
      <pre id="out"></pre>
      <script>
        const btn = document.getElementById('btn');
        const out = document.getElementById('out');
        btn.onclick = async () => {
          out.textContent = 'Calling /api/get ...';
          try {
            const res = await fetch('/api/get?demo=true');
            const json = await res.json();
            out.textContent = JSON.stringify(json, null, 2);
            out.className = 'ok';
          } catch (e) {
            out.textContent = e.toString();
            out.className = 'err';
          }
        };
      </script>
    </body>
    </html>
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: demo
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: html
          configMap:
            name: frontend-html